name: HeartChanger
version: 1.0.1
main: net.nicc0.heartchanger.hcPlugin
author: Nicc0
depend: [ProtocolLib]
description: Change heart to hardcore mode without changing game mode.
permissions:
    heartchanger.*:
        description: Gives access to all heart types
        default: op
        children:
            heartchanger.normal: true
            heartchanger.hardcore: true
            heartchanger.golden: true
            heartchanger.dark: true
            heartchanger.poisoned: true
    heartchanger.normal:
        description: Allows the player to change hearts to normal
        default: true
    heartchanger.hardcore:
        description: Allows the player to change hearts to hardcore ones 
    heartchanger.golden:
        description: Allows the player to change hearts to golden ones 
    heartchanger.dark:
        description: Allows the player to change hearts to dark ones 
    heartchanger.poisoned:
        description: Allows the player to change hearts to poisoned ones
        